image: node:12

pages:
  script:
    - echo $CI_JOB_STAGE
    - echo $HELLO
    - npm install
    - npm run import-csv
    - npm run build
  artifacts:
    paths:
      - dist
  cache:
    paths:
      - node_modules
  only:
    - master
