global:
  name: AI Landscape
  short_name: Project
  repo: 'https://gitlab.com/opendatahub/odh-landscape.git'
  website: 'https://opendatahub.io/landscape'
  short_domain: https://opendatahub.io/landscape
  company_url: 'https://opendatahub.io/'
  email: contributors-owner@lists.opendatahub.io
  meta:
    title: AI Landscape
    fb_admin:
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@opendatahubio'
    google_site_verification:
    ms_validate:
  membership: Open Data Hub Partner
  flags:
    cncf_sandbox: false
    companies: Open Data Hub Partner
twitter:
  search: landscape.project.org
  url: 'https://landscape.project.org'
  text: AI Landscape
relation:
  label: Relationship
  url: odh-relation
  values:
    - id: implementation
      label: Implemented
      children:
        - id: community
          label: Community Operator
          tag: Community Operator
          color: '#3570af'
        - id: certified
          label: Certified Operator
          tag: Certified Operator
          color: '#00cbff'
        - id: ubi
          label: UBI Implemented
          tag: UBI Implemented
          color: '#d1f7ff'
    - id: odh
      label: Open Data Hub
      tag: Open Data Hub
    - id: false
      label: No Status
      url: 'no'
status:
  label: Status
  url: status
  values:
    - id: odh
      label: Open Data Hub
      tag: Open Data Hub
    - id: implemented
      label: Implemented
      children:
        - id: community
          label: Community Operator
          tag: Community Operator
        - id: certified
          label: Certified Operator
          tag: Certified Operator
        - id: ubi
          label: UBI Implemented
          tag: UBI Implemented
    - id: false
      label: No Status
      url: 'no'
membership:
  General:
    name: Project
    label: Member
    funding: General
  linux_foundation:
    name: LF
    label: Project
    funding: Linux Foundation
    crunchbase_and_children: 'https://www.crunchbase.com/organization/linux-foundation'
  'false':
    funding: 'No'
home:
  header: >
    <h1>AI Landscape</h1>
  footer:
ads: []
presets:
  - url: /license=open-source
    label: Open source projects
  - url: /status=odh
    label: Open Data Hub projects
  - url: /status=implemented,community,certified,ubi
    label: Operator implemented
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /format=card-mode&grouping=category
    label: Cards in categories
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: AI Landscape
    fullscreen_header: See the interactive landscape at l.project.org
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1115
      height: 770
    fullscreen_size:
      width: 1155
      height: 840
    elements:
      # height = 32 * rows + 20
      - type: HorizontalCategory
        category: AI and Machine Learning Lifecycle
        rows: 6
        width: 1060
        height: 232
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
      - type: HorizontalCategory
        category: Data Analysis
        rows: 3
        width: 1060
        height: 136
        top: 252
        left: 0
        color: 'rgb(104, 145, 145)'
      - type: HorizontalCategory
        category: Data Processing
        rows: 5
        width: 1060
        height: 200
        top: 408
        left: 0
        color: 'rgb(74, 131, 104)'
      - type: HorizontalCategory
        category: Data Store
        rows: 2
        width: 1060
        height: 104
        top: 628
        left: 0
        color: 'rgb(108, 135, 75)'
      - type: HorizontalCategory
        category: Infrastructure
        rows: 2
        width: 1060
        height: 104
        top: 752
        left: 0
        color: 'rgb(142, 209, 216)'
      - type: VerticalCategory
        category: Data Governance and Security
        cols: 5
        width: 220
        height: 856
        top: 0
        left: 1080
        color: 'rgb(130, 207, 231)'        
test:
  header: AI Landscape
  section: Project Foundation Members
  logo: ibm.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
